<?php

/**
 *  @file
 *  Integrating Galleria with Views Slideshow.
 */


/**
 * Implements hook_library_info().
 */
function views_slideshow_galleria_library_info()
{
  $library_path = backdrop_get_path('module', 'views_slideshow_galleria') . '/library';
  $libraries['galleria'] = array(
    'title' => 'Galleria',
    'website' => 'http://galleria.io',
    'version' => '1.5.7',
    'js' => array(
      $library_path . '/galleria/galleria-1.5.7.js' => array(),
    ),
  );
  return $libraries;
}


/**
 *  Implements hook_theme().
 */
function views_slideshow_galleria_theme() {
  return array(
    'views_slideshow_galleria_main_frame' => array(
      'variables' => array('vss_id' => NULL, 'view' => NULL, 'settings' => NULL, 'rows' => NULL),
      'template' => 'views-slideshow-galleria-main-frame',
      'file' => 'views_slideshow_galleria.theme.inc',
    ),
  );
}

